#!/usr/bin/env python3
"""
Public-safe config helper for first-time self-hosted deployments.

This script intentionally does not know production secrets. It asks for local
values and writes config.env only when the target file does not already exist,
unless --force is passed.
"""

from __future__ import annotations

import argparse
from pathlib import Path


PROMPTS = [
    ("API_ID", "Telegram API ID"),
    ("API_HASH", "Telegram API hash"),
    ("BOT_TOKEN", "Main bot token"),
    ("HELPER_BOT_TOKEN", "Helper bot token"),
    ("AUTH_CHANNEL", "Authorized channel IDs, comma-separated"),
    ("DATABASE", "MongoDB URIs, comma-separated tracking first then storage"),
    ("TMDB_API", "TMDb API key"),
    ("BASE_URL", "Public HTTPS base URL"),
    ("DEFAULT_ADDON_TOKEN", "Default addon token"),
    ("ADMIN_USERNAME", "Admin username"),
    ("ADMIN_PASSWORD", "Admin password"),
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a Telegram-Stremio config.env")
    parser.add_argument("--output", default="config.env", help="Output config path")
    parser.add_argument("--force", action="store_true", help="Overwrite existing config")
    args = parser.parse_args()

    output = Path(args.output)
    if output.exists() and not args.force:
        raise SystemExit(f"{output} already exists. Use --force to overwrite.")

    values = {}
    print("Telegram-Stremio setup wizard")
    print("Leave a value empty only if the feature is optional in your deployment.\n")
    for key, label in PROMPTS:
        values[key] = input(f"{label}: ").strip()

    lines = [
        "# Generated by deploy/setup_wizard.py",
        'TELEGRAM_PROXY_ENABLED="false"',
        'TELEGRAM_PROXY_SCHEME="socks5"',
        'TELEGRAM_PROXY_HOST="warp_proxy"',
        'TELEGRAM_PROXY_PORT="40000"',
        'WARP_CONTROL_COMMAND=""',
        'WARP_CONTROL_URL=""',
        'WARP_CONTROL_SECRET=""',
        'REPLACE_MODE="true"',
        'HIDE_CATALOG="false"',
        'PARALLEL="3"',
        'PRE_FETCH="3"',
        'TELEGRAM_CDN_ENABLED="true"',
        'IPTV_ENABLED="true"',
        'IPTV_COUNTRY_CODES=""',
        'ANIME_CHANNELS=""',
        'GLOBAL_SEARCH="false"',
        'GLOBAL_SEARCH_CHANNELS=""',
    ]
    for key, value in values.items():
        escaped = value.replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {output}")
    print("Next: review config.env, then run: docker compose up -d --build")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
